[pyprland]
plugins = ["scratchpads"]

[scratchpads.volume]
animation = "fromRight"
command = "pavucontrol"
class = "org.pulseaudio.pavucontrol"
size = "40% 90%"
unfocus = "hide"
lazy = true

[scratchpads.wifi]
animation = "fromRight"
command = "kitty --class kitty-wifi impala"
class = "kitty-wifi"
size = "40% 90%"
unfocus = ""
lazy = true